let shopItemsData = [
  {
    id: "pennylane",
    name: "Penny Lane",
    price: 30000,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/selling-2.jpg",
  },
  {
    id: "newbury",
    name: "Newbury",
    price: 18900,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/selling-1.jpg",
  },
  {
    id: "jstreet",
    name: "J Street",
    price: 14000,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/selling-3.jpg",
  },
  {
    id: "sweetnancy",
    name: "Sweet Nancy",
    price: 7200,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/img-1.jpg",
  },
  {
    id: "mixedtulips",
    name: "Mixed Tulips",
    price: 4800,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/img-2.jpg",
  },
  {
    id: "sunshineinbloom",
    name: "Sunshine In Bloom",
    price: 6900,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/img-3.jpg",
  },
  {
    id: "fascination",
    name: "Fascination",
    price: 9100,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/img-4.jpg",
  },
  {
    id: "parkavenue",
    name: "Park Avenue",
    price: 28000,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/img-5.jpg",
  },
  {
    id: "igorsspecial",
    name: "Igor's special",
    price: 700,
    desc: "Великолепный пивной букет специально по заказу Игоря Мироненко. С любовью от Floritta.",
    img: "images/img-6.jpg",
  },
  {
    id: "babysbreath",
    name: "Baby's Breath In A Vase",
    price: 3300,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/img-7.jpg",
  },
  {
    id: "rosedelight",
    name: "Roses Delight",
    price: 4500,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/img-8.jpg",
  },
  {
    id: "120pink",
    name: "120 Pink, Red And White Tulips",
    price: 21000,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/img-9.jpg",
  },
];
